# Generated by Django 4.1.5 on 2023-01-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_ad_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
